name: 'gruploader release'
description: 'Upload the specified file or build file to the releases attachment'
author: 'zhiqiang <zhiqiang2033@gmail.com>'

inputs:
  github_token:
    description: 'GitHub token used to authenticate and upload release assets.'
    required: true
    default: ''

  origin_url:
    description: 'The Git repository URL to operate on.'
    required: false
    default: ''

  cname_domain:
    description: 'Custom domain for GitHub Pages deployment (CNAME).'
    required: false
    default: ''

  action:
    description: 'Specifies the language used for building the project. Default is Go.'
    required: false
    default: 'golang'

  extra_files:
    description: 'Additional files to include in the release archive.'
    required: false
    default: ''

  maingo:
    description: 'Main Go entry file for compilation.'
    required: false
    default: 'main.go'

  goos:
    description: 'GOOS value used for cross-compiling Go binaries.'
    required: true
    default: ''

  goarch:
    description: 'GOARCH value used for cross-compiling Go binaries.'
    required: true
    default: ''

  goversion:
    description: 'Go compiler version to use.'
    required: false
    default: ''

  repository:
    description: 'The GitHub repository to operate on.'
    required: false
    default: ''

  tag:
    description: 'The release tag to publish.'
    required: false
    default: ''

  bin_name:
    description: 'Name of the output binary file.'
    required: false
    default: ''

  build_flags:
    description: 'Additional flags to pass to the Go build command.'
    required: false
    default: ''

  goamd64:
    description: 'GOAMD64 value for advanced Go builds on x86_64.'
    required: false
    default: ''

  goarm:
    description: 'GOARM value for ARM architecture builds.'
    required: false
    default: ''

  gomips:
    description: 'GOMIPS value for MIPS architecture builds.'
    required: false
    default: ''

  ldflags:
    description: 'Flags passed to the Go linker.'
    required: false
    default: ''

  npm_install_pkg:
    description: 'Command to install npm dependencies.'
    required: false
    default: 'npm install'

  npm_build_command:
    description: 'Command to run the npm build process.'
    required: false
    default: 'npm run build'

  npm_build_dist:
    description: 'Output directory generated by the npm build process.'
    required: false
    default: 'dist'


outputs:
  release_asset_dir:
    description: 'Release file directory provided for use by other workflows'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.origin_url }}
    - ${{ inputs.cname_domain }}
    - ${{ inputs.gruploader_version }}
    - ${{ inputs.gruploader_cloud }}
    - ${{ inputs.overwrite }}
    - ${{ inputs.retry }}
    - ${{ inputs.extra_files }}
    - ${{ inputs.maingo }}
    - ${{ inputs.goos }}
    - ${{ inputs.goarch }}
    - ${{ inputs.repository }}
    - ${{ inputs.tag }}
    - ${{ inputs.bin_name }}
    - ${{ inputs.build_flags }}
    - ${{ inputs.goamd64 }}
    - ${{ inputs.goarm }}
    - ${{ inputs.gomips }}
    - ${{ inputs.ldflags }}
    - ${{ inputs.npm_install_pkg }}
    - ${{ inputs.npm_build_command }}
    - ${{ inputs.npm_build_dist }}

branding:
  icon: 'package'
  color: 'blue'