#!/bin/bash -eux

check_empty "GRUPLOADER_COMMAND" "${GRUPLOADER_COMMAND}"
INPUT_EXTRA_FILES="${INPUT_EXTRA_FILES:-""}"
INPUT_BIN_NAME="${INPUT_BIN_NAME:-"web"}"
INPUT_NPM_INSTALL_PKG="${INPUT_NPM_INSTALL_PKG:-"npm install"}"
INPUT_NPM_BUILD_COMMAND="${INPUT_NPM_BUILD_COMMAND:-"npm run build"}"
INPUT_NPM_BUILD_DIST="${INPUT_NPM_BUILD_DIST:-"dist"}"


${INPUT_NPM_INSTALL_PKG} && ${INPUT_NPM_BUILD_COMMAND}

if [ ! -z "${INPUT_EXTRA_FILES}" ]; then
  cp -r ${INPUT_EXTRA_FILES} ${INPUT_NPM_BUILD_DIST}/
fi

cd ${INPUT_NPM_BUILD_DIST}

COMPRESSION_NAME="${INPUT_BIN_NAME}.tar.gz"

tar cvfz "${COMPRESSION_NAME}" *

${GRUPLOADER_COMMAND} -f ${COMPRESSION_NAME}