name: docker-image

on:
  push:
    tags:
      - 'v*' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name without "v"
        id: tag
        run: |
          RAW_TAG="${GITHUB_REF##refs/tags/}"
          CLEAN_TAG="${RAW_TAG#v}"
          echo "tag=$CLEAN_TAG" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push gruploader Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.build
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/pkg6/gruploader:${{ steps.tag.outputs.tag }}
            ghcr.io/pkg6/gruploader:latest
